[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
upload_speed = 115200
build_flags = -I/home/john/Arduino/sketchbook/libraries/credentials

; Added ropg/ezTime to your cloud download checklist
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0
    knolleary/PubSubClient
    ropg/ezTime
